### ISSUE TITLE
What is max_bin_diag?

### ISSUE THREAD

**Issue by WHlTE-N0lSE** [zdaxie/PixPro#1]
Thanks for open source. What is the function of max_bin_diag?

**Comment by zdaxie** [comment]
Thanks for your attention to our work. As for `max_bin_diag` you mentioned, I think what you are referring to is the variable [here](https://github.com/zdaxie/PixPro/blob/main/contrast/models/PixPro.py#L71).

Since we have two feature maps generated from two different views, the original view sizes corresponding to these two feature maps are not consistent. Therefore, we need to first map the coordinates of the feature map back to the original image coordinates, and then use the diagonal length of the feature map bin to normalize and determine the positive and negative samples accordingly. But we have two different diagonal lengths, so in the implementation we use the larger one of two diagonal lengths, which is the `max_bin_diag` you mentioned. For details on how to determine the positive and negative samples, please refer to the complete [function](https://github.com/zdaxie/PixPro/blob/main/contrast/models/PixPro.py#L44) and **Sec3.1, subsection -  Pixel Contrast** of the paper.
